# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'manager.ui'
#
# Created: Wed Jul 10 17:51:32 2013
#      by: pyside-uic 0.2.14 running on PySide 1.1.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(586, 490)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.serverOutputTextEdit = QtGui.QTextEdit(self.centralwidget)
        self.serverOutputTextEdit.setReadOnly(True)
        self.serverOutputTextEdit.setObjectName("serverOutputTextEdit")
        self.verticalLayout_2.addWidget(self.serverOutputTextEdit)
        self.sendCommandLine = QtGui.QLineEdit(self.centralwidget)
        self.sendCommandLine.setObjectName("sendCommandLine")
        self.verticalLayout_2.addWidget(self.sendCommandLine)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 1, 0, 1, 1)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.launchButton = QtGui.QPushButton(self.centralwidget)
        self.launchButton.setObjectName("launchButton")
        self.verticalLayout_3.addWidget(self.launchButton)
        self.shutdownButton = QtGui.QPushButton(self.centralwidget)
        self.shutdownButton.setObjectName("shutdownButton")
        self.verticalLayout_3.addWidget(self.shutdownButton)
        self.gridLayout_2.addLayout(self.verticalLayout_3, 0, 1, 1, 1)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.serverAddressLine = QtGui.QLineEdit(self.centralwidget)
        self.serverAddressLine.setEnabled(False)
        self.serverAddressLine.setObjectName("serverAddressLine")
        self.verticalLayout_4.addWidget(self.serverAddressLine)
        self.gridLayout_2.addLayout(self.verticalLayout_4, 0, 0, 1, 1)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_6.addWidget(self.label_3)
        self.typeComboBox = QtGui.QComboBox(self.centralwidget)
        self.typeComboBox.setObjectName("typeComboBox")
        self.typeComboBox.addItem("")
        self.typeComboBox.addItem("")
        self.typeComboBox.addItem("")
        self.typeComboBox.addItem("")
        self.verticalLayout_6.addWidget(self.typeComboBox)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem)
        self.gridLayout_2.addLayout(self.verticalLayout_6, 1, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 586, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Minecraft EC2 Server Manager", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Server Ouput", None, QtGui.QApplication.UnicodeUTF8))
        self.launchButton.setText(QtGui.QApplication.translate("MainWindow", "Launch", None, QtGui.QApplication.UnicodeUTF8))
        self.shutdownButton.setText(QtGui.QApplication.translate("MainWindow", "Shutdown", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Server Address", None, QtGui.QApplication.UnicodeUTF8))
        self.serverAddressLine.setText(QtGui.QApplication.translate("MainWindow", "54.235.158.237", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Choose Instance Type", None, QtGui.QApplication.UnicodeUTF8))
        self.typeComboBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "t1.micro (1 player)", None, QtGui.QApplication.UnicodeUTF8))
        self.typeComboBox.setItemText(1, QtGui.QApplication.translate("MainWindow", "m1.small (1 - 2 players)", None, QtGui.QApplication.UnicodeUTF8))
        self.typeComboBox.setItemText(2, QtGui.QApplication.translate("MainWindow", "m1.medium (3 - 10 players)", None, QtGui.QApplication.UnicodeUTF8))
        self.typeComboBox.setItemText(3, QtGui.QApplication.translate("MainWindow", "m1.large (10+ or excessive lag)", None, QtGui.QApplication.UnicodeUTF8))

